#!/usr/bin/env bash


#sudo apt-get install libbz2-dev
# on cluster: cluster-linux.rz.rwth-aachen.de
# To ensure gcc/5.3 is loaded: module load gcc/5

cd src/realpath; ./install.sh ; cd ../..; source ./setupenv realpath-1.0
# cd src/gcc; ./install.sh ; cd ../..; source ./setupenv gcc-5.3.0
cd src/libcurl; ./install.sh ; cd ../..; source ./setupenv libcurl-7.45.0
cd src/libeigen; ./install.sh ; cd ../..; source ./setupenv libeigen-3.2.6
cd src/libevent; ./install.sh ; cd ../..; source ./setupenv libevent-2.0.22-stable
cd src/ncurses; ./install.sh ; cd ../..; source ./setupenv ncurses-6.0
cd src/pv; ./install.sh ; cd ../..; source ./setupenv pv-1.6.0
cd src/boost; ./install.sh ; cd ../..; source ./setupenv boost-1.60.0
cd src/m4; ./install.sh ; cd ../..; source ./setupenv m4-1.4.17
cd src/bison; ./install.sh ; cd ../..; source ./setupenv bison-3.0.4
cd src/autoconf; ./install.sh ; cd ../..; source ./setupenv autoconf-2.69
cd src/cmake ; ./install.sh ; cd ../..; source ./setupenv cmake-3.4.0-rc1
cd src/parallel; ./install.sh ; cd ../..; source ./setupenv parallel-2015922
cd src/gflags; ./install.sh ; cd ../..; source ./setupenv gflags-`date +%Y-%m-%d`
cd src/glog; ./install.sh ; cd ../..; source ./setupenv glog-0.3.3
cd src/gtest; ./install.sh ; cd ../..; source ./setupenv gtest-`date +%Y-%m-%d`
cd src/kenlm; ./install.sh ; cd ../..; source ./setupenv kenlm-`date +%Y-%m-%d`
cd src/openfst; ./install.sh ; cd ../..; source ./setupenv openfst-1.5.0
cd src/gawk; ./install.sh ; cd ../..; source ./setupenv gawk-4.1.3
cd src/sparsehash; ./install.sh ; cd ../..; source ./setupenv sparsehash-2.0.3
cd src/zlib; ./install.sh ; cd ../..; source ./setupenv zlib-1.2.8
cd src/libbzip2; ./install.sh ; cd ../..; source ./setupenv bzip2-1.0.6
cd src/libunwind; ./install.sh ; cd ../..; source ./setupenv libunwind-1.1
#cd src/tmux; ./install.sh ; cd ../..; source ./setupenv tmux-2.1


#if which realpath >/dev/null; then
#    echo realpath exists
#else
#    echo realpath not exists
#    echo Installing realpath
#    cd src/realpath ; ./install.sh ; cd ../.. ; export PATH=$PATH:`pwd`/build/realpath-1.0/bin/
#fi

#cd src/gcc; ./install.sh ; cd ../.. ;export PATH=$PATH:`pwd`/build/gcc-4.9.2/bin/
#cd src/bison ; ./install.sh ; cd ../..
#cd src/autoconf; ./install.sh ; cd ../..
#cd src/realpath ; ./install.sh ; cd ../..
#cd src/cmake ; ./install.sh ; cd ../..
#cd src/m4 ; ./install.sh ; cd ../..
#cd src/gawk ; ./install.sh ; cd ../..
#cd src/boost ; ./install.sh ; cd ../..
#cd src/thrift ; ./install.sh ; cd ../..
#cd src/stxxl ; ./install.sh ; cd ../..
#cd src/openfst ; ./install.sh ; cd ../..

