#!/usr/bin/env bash

#sudo apt-get install libbz2-dev

if which realpath >/dev/null; then
    echo realpath exists
else
    echo realpath not exists
    echo Installing realpath
    cd src/realpath ; ./install.sh ; cd ../.. ; export PATH=$PATH:`pwd`/build/realpath-1.0/bin/
fi

#cd src/realpath ; ./install.sh ; cd ../..
#cd src/cmake ; ./install.sh ; cd ../..
#cd src/m4 ; ./install.sh ; cd ../..
#cd src/bison ; ./install.sh ; cd ../..
#cd src/gawk ; ./install.sh ; cd ../..
#cd src/boost ; ./install.sh ; cd ../..
#cd src/thrift ; ./install.sh ; cd ../..
#cd src/stxxl ; ./install.sh ; cd ../..
#cd src/openfst ; ./install.sh ; cd ../..

