#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo >&2 "usage: program"
  exit 1
fi

ls build | grep $1 | \
  awk -F '-' '{ if (NF>1) { printf("%s\t%s\n", $2, $1) }}' | \
  sort -k2,2g | \
  awk '{ 
    if (NR==1) { 
      OLDVERSION=$1;
      OLDNAME=$2
    }; 
    if (OLDNAME!=$2) {
      print OLDNAME, OLDVERSION;
      OLDVERSION=$1;
      OLDNAME=$2
    }
  }
  END {
    print $1, $2
  }' | \
  awk '{printf("%s-%s\n", $2, $1)}'

