#!/usr/bin/env bash

BASEDIR="$( cd "$( dirname "${BASH_SOURCE:-$0}" )" && pwd )"

# SORT VERSION NUMBERS

${BASEDIR}/installed | sort -k2,2 -k1,1r | \
  awk '{ 
    if (NR==1) { 
      OLDVERSION=$1;
      OLDNAME=$2
      OLDFULL=$3
    }; 
    if (OLDNAME!=$2) {
      print OLDFULL
      OLDVERSION=$1;
      OLDNAME=$2
      OLDFULL=$3
    }
  }
  END {
    print OLDFULL
  }'
