#!/usr/bin/env bash

UNAME=$(uname)

if [ $# -lt 1 ]; then
  echo >&2 "missing subdir"
  exit 1
else
  while [ $# -ge 1 ]; do
    BASEDIR="$( cd "$( dirname "${BASH_SOURCE:-$0}" )" && pwd )"/build/$1
    if [ -d ${BASEDIR}/bin ]; then
      export PATH=${BASEDIR}/bin:${PATH}
    fi

    if [ -d ${BASEDIR}/include ]; then
      export CPATH=${BASEDIR}/include:${CPATH}
      export CPPFLAGS="${CPPFLAGS} -isystem${BASEDIR}/include"
      export CFLAGS="${CFLAGS} -I${BASEDIR}/include"
    fi

    if [ -d ${BASEDIR}/lib ]; then
      export LDFLAGS="${LDFLAGS} -L${BASEDIR}/lib"

      # darwin needs a different environment variable
      if [ ${UNAME} = "Darwin" ]; then
        export DYLD_LIBRARY_PATH=${BASEDIR}/lib:${DYLD_LIBRARY_PATH}
      else
        export LD_LIBRARY_PATH=${BASEDIR}/lib:${LD_LIBRARY_PATH}
      fi

      export LIBRARY_PATH=${BASEDIR}/lib:${LIBRARY_PATH}
    fi

    if [ -d ${BASEDIR}/lib64 ]; then
      export LDFLAGS="${LDFLAGS} -L${BASEDIR}/lib64"

      # darwin needs a different environment variable
      if [ ${UNAME} = "Darwin" ]; then
        export DYLD_LIBRARY_PATH=${BASEDIR}/lib64:${DYLD_LIBRARY_PATH}
      else
        export LD_LIBRARY_PATH=${BASEDIR}/lib64:${LD_LIBRARY_PATH}
      fi

      export LIBRARY_PATH=${BASEDIR}/lib64:${LIBRARY_PATH}
    fi

    if [ -d ${BASEDIR}/share/man ]; then
      export MANPATH=${BASEDIR}/share/man:${MANPATH}
    fi

    if [ -d ${BASEDIR}/share/info ]; then
      export INFODIR=${BASEDIR}/share/info:${INFODIR}
    fi

    if [ -d ${BASEDIR}/share/info ]; then
      export ACLOCAL_PATH=${BASEDIR}/share/aclocal:${ACLOCAL_PATH}
    fi
    
    if [ -d ${BASEDIR}/lib/python2.7/site-packages ]; then
      export PYTHONPATH="${PYTHONPATH}:${BASEDIR}/lib/python2.7/site-packages"
    fi

    if [ -d ${BASEDIR}/lib/python2.6/site-packages ]; then
      export PYTHONPATH="${PYTHONPATH}:${BASEDIR}/lib/python2.6/site-packages"
    fi

    shift
  done
fi
